-- AlterTable
ALTER TABLE "shifts" ADD COLUMN     "breakMinutes" INTEGER DEFAULT 0,
ADD COLUMN     "bufferMinutes" INTEGER DEFAULT 0,
ADD COLUMN     "consultationDuration" INTEGER DEFAULT 0,
ADD COLUMN     "consultationTypes" JSONB,
ADD COLUMN     "department" TEXT,
ADD COLUMN     "doctorId" TEXT,
ADD COLUMN     "emergencySlotReserved" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "endTime" TEXT,
ADD COLUMN     "hospitalBranch" TEXT,
ADD COLUMN     "hospitalId" TEXT,
ADD COLUMN     "isAvailable" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "maxPatients" INTEGER DEFAULT 0,
ADD COLUMN     "repeatDays" JSONB,
ADD COLUMN     "repeatInterval" TEXT,
ADD COLUMN     "roomNumber" TEXT,
ADD COLUMN     "shiftDate" TEXT,
ADD COLUMN     "shiftType" TEXT,
ADD COLUMN     "slots" JSONB,
ADD COLUMN     "startTime" TEXT,
ADD COLUMN     "walkInAllowed" BOOLEAN NOT NULL DEFAULT false;
